---
- hosts: kg_ad
  vars:
    ps_domainname: "pyro.testrealm.local"
    ps_domainnetbios: "pyro"
    ps_domainadmin_user: "pyro"
    ps_domainadmin_pass: "V@gran7"
    ps_safemodeadmin_user: "safepyro"
    ps_safemodeadmin_pass: "V@gran7"
    ps_users:
      - { name: 'ichiban', pass: 'ichiV@gran7' }
      - { name: 'niban', pass: 'niV@gran7' }
      - { name: 'sanban', pass: 'sanV@gran7'}
      - { name: 'yonban', pass: 'yonV@gran7'}
  gather_facts: false
  tasks:
  - name: Make sure the LCM refresh mode is disabled
    win_lcm5:
      refresh_mode: "Disabled"
    tags:
      - Config
  - name: Download xActiveDirectory
    win_oneget:
      name: "xActiveDirectory"
    tags:
      - Oneget
  - name: Download xNetworking
    win_oneget:
      name: "xNetworking"
    tags:
      - Oneget
  - name: Install ADDS and RSAT
    win_feature:
      name: "AD-Domain-Services,RSAT-AD-Tools"
    tags:
      - WindowsFeature
  - name: Init Domain
    win_ad_xaddomain:
      DomainName: "{{ ps_domainname }}"
      DomainNetbiosName: "{{ ps_domainnetbios }}"
      DomainAdministratorCredential_username: "{{ ps_domainadmin_user }}"
      DomainAdministratorCredential_password: "{{ ps_domainadmin_pass }}"
      SafemodeAdministratorPassword_username: "{{ ps_safemodeadmin_user }}"
      SafemodeAdministratorPassword_password: "{{ ps_safemodeadmin_pass }}"
    tags:
      - DomainInit
    notify:
      - Reboot Server
  - meta: flush_handlers
  - name: Pause for a min
    pause:
      minutes: 1
  - name: Add Users
    win_ad_xaduser:
      DomainName: "{{ ps_domainname }}"
      UserName: "{{ item.name }}"
      Password_username: "{{ item.name }}"
      Password_password: "{{ item.pass }}"
    with_items: "{{ ps_users }}"
    tags:
      - AddUsers
  - name: Promote Users
    win_ad_xadgroup:
      GroupName: "Domain Admins"
      MembersToInclude: "ichiban, niban"
    tags:
      - PromoteUsers
  - name: Change DNS Address
    win_pc_xdnsserveraddress:
      Address: "8.8.8.8"
      InterfaceAlias: "Ethernet 2"
      AddressFamily: "IPv4"
  handlers:
  - name: Reboot Server
    win_reboot:
      shutdown_timeout_sec: 600
      reboot_timeout_sec: 600
