---
  - hosts: kg_ts1:kg_ts2
    gather_facts: false
    vars:
      ps_softwares:
        - notepadplusplus
        - 7zip
        - firefox
        - googlechrome
        - filezilla
        - ccleaner
        - adobereader
        - keepassx
        - foxitreader
        - pdf24
        - cutepdf
        - vcredist2010
        - vcredist2005
    tasks:
    - name: Make sure the LCM refresh mode is disabled
      win_lcm5:
        refresh_mode: "Disabled"
    - name: Install Terminal Server related Softwares
      win_chocolatey: name="{{ item }}" state=present
      with_items: "{{ ps_softwares }}"
    - name: Install Net3
      win_feature:
        name: "Net-Framework-Core"
    - name: Install DotNet Package
      win_chocolatey:
        name: "{{ item }}"
        state: present
      with_items:
        - "dotnet4.0"
        - "dotnet4.5"
      tags:
        - PreReqs
    - name: Install SQLCE
      win_pc_package:
        Name: "Microsoft SQL Server Compact 4.0 x64 ENU"
        Path: 'C:\vagrant\ansible\setup\tssetup\Prerequisites\MsSqlServerCE\SSCERuntime_x64-ENU.msi'
        ProductId: "{8424B163-D1E0-48B7-88A2-C7A61767B3D7}"
        Arguments: '/qn'
      tags:
        - SQLCE
    - name: Install VSTO
      win_pc_package:
        Name: "Microsoft Visual Studio 2010 Tools for Office Runtime (x64)"
        Path: 'C:\vagrant\ansible\setup\tssetup\Prerequisites\VSTO 2010 Runtime\vstor40_x64.exe'
        ProductId: "{C3600AE6-93A0-3DB7-B7AA-45BD58F133B5}"
        Arguments: '/qn'
      tags:
        - VSTO
    - name: Install SQLCLI
      win_pc_package:
        Name: "Microsoft SQL Server 2008 R2 Native Client"
        Path: 'C:\vagrant\ansible\setup\tssetup\Prerequisites\SQLNativeClient\2008R2\x64\sqlncli.msi'
        ProductId: "{2180B33F-3225-423E-BBC1-7798CFD3CD1F}"
        Arguments: '/qn IACCEPTSQLNCLILICENSETERMS=YES'
      tags:
        - SQLCLI
    - name: Install MAS
      win_pc_package:
        Name: "Sage 100 ERP 2015 Workstation"
        Path: 'C:\vagrant\ansible\setup\tssetup\Sage 100 ERP 2015 Workstation.msi'
        ProductId: "{0126AFE4-F229-4BDE-8ED5-225C52DB038F}"
        Arguments: '/quiet /l*v "C:\Windows\Temp\mas.log" SAGEPORTID="9998" SAGESERVERNAME="HSYMAS03" SRCSERVERPATH="C:\vagrant\ansible\setup\tssetup\" INSTALLDIR="C:\Sage\Sage 100 ERP 2015 Worstation\MAS90\"'
    #- name: Copy the License
      #win_copy:
        #src: "tssetup/massetup/MAS90/Home/Lib/Keys/ACTIVATE.PVX"
        #dest: '"C:\\Sage\\Sage 100 ERP 2015 Worstation\\MAS90\\Home\\Lib\\Keys\\"'
