---
- hosts: kg_strgutl:kg_ts1:kg_ts2
  gather_facts: true
  vars:
    ps_domainname: "pyro.testrealm.local"
    ps_domainadmin_user: "pyro\\ichiban"
    ps_domainadmin_pass: "ichiV@gran7"
    ps_iface:
      - { name: 'ichiban', dns: '10.255.10.20' }
      - { name: 'Ethernet 2', dns: '10.255.10.20' }
    ps_domain_dict: {"10.255.10.20":"KGAD", "10.255.10.21":"KGSTRGUTL", "10.255.10.22":"KGTS1", "10.255.10.23":"KGTS2"}

  tasks:
  - name: Make sure the LCM refresh mode is disabled
    win_lcm5:
      refresh_mode: "Disabled"
    tags:
      - Config
  - name: Download xNetworking
    win_oneget:
            name: "xNetworking"
    tags:
      - Oneget
  - name: Download xComputerManagement
    win_oneget:
            name: "xComputerManagement"
    tags:
      - Oneget
  - name: Change DNS Address
    win_pc_xdnsserveraddress:
      Address: "{{ item.dns }}"
      InterfaceAlias: "{{ item.name }}"
      AddressFamily: "IPv4"
    with_items: "{{ ps_iface }}"
  - name: Rename and Join Domain
    win_pc_xcomputer:
      Name: "{{ ps_domain_dict[inventory_hostname] }}"
      DomainName: "{{ ps_domainname }}"
      Credential_username: "{{ ps_domainadmin_user }}"
      Credential_password: "{{ ps_domainadmin_pass }}"
    tags:
      - CompInit
    notify:
      - Reboot Server
  - meta: flush_handlers
  handlers:
  - name: Reboot Server
    win_reboot:
      shutdown_timeout_sec: 600
      reboot_timeout_sec: 600
