---
  - name: Setup Guacamole
    include: ./ps_guac_new.yml
  - name: Disable nla so Guac work
    include: ./ps_disable_nla.yml
  - name: Setup and Init ADDC
    include: ./ps_ad_setup.yml
  - pause:
    minutes: 2
  - name: Join others to the Domain
    include: ./ps_join_domain.yml
  - name: Setup Merit Box
    include: ./ps_merit_box.yml
  - name: Setup Terminal Server
    include: ./ps_terminal_server.yml
