---
  - name: Setup Guacamole
    include: ./guacamole/ps_guac_new.yml
  - name: Disable nla so Guac work
    include: ./utilities/ps_disable_nla.yml
  - name: Setup and Init ADDC
    include: ./domain/ps_ad_setup.yml
  - name: Join others to the Domain
    include: ./domain/ps_join_domain.yml
  - name: Setup Roaming Profile
    include: ./profiles/ps_setup_profiles.yml

#  - name: Setup Merit Box
#    include: ./ps_merit_box.yml
#  - name: Setup Terminal Server
#    include: ./ps_terminal_server.yml
