---
  - hosts: kg_strgutl
    vars:
      ps_softwares:
        - notepadplusplus
        - 7zip
        - googlechrome
        - filezilla
        - ccleaner
        - adobereader
        - pdf24
        - cutepdf
        - winscp
        - mssqlservermanagementstudio2014express
    tasks:
    - name: Make sure the LCM refresh mode is disabled
      win_lcm5:
        refresh_mode: "Disabled"
   #- name: Download GraniResource
     # win_oneget:
       # name: "GraniResource"
    #- name: Schdule Merit Task
     # win_pc_cschduletask:
       # Ensure: Present
       # TaskName: Notepad Schduler
       # Execute:  notepad
       # ScheduledAt: 00:00:00
       # Daily: true
       # Compatibility: "Win8"
       # Disable: false
    - name: Install RDS
      win_feature:
        name: "RDS-RD-Server"
    - name: Download xSQLPs
      win_oneget:
        name: "xSQLPs"
    - name: Install SQLServer
      win_pc_xsqlserverinstall:
        InstanceName: "MSSQLSERVER"
        SourcePath: 'C:\vagrant\ansible\setup\sql'
        Features: "SQL, Tools"
    - name: Install SQLExpress-Studio
      win_chocolatey:
        name: "mssqlservermanagementstudio2014express"
        state: present
    - name: Install Merit Box related Softwares
      win_chocolatey: name="{{ item }}" state=present
      with_items: "{{ ps_softwares }}"
