---
  - name: Setup Guacamole
    include: ./ps_guac_setup.yml 
  - name: Setup and Init ADDC
    include: ./ps_ad_setup.yml
  - name: Join others to the Domain
    include: ./ps_join_domain.yml
  - name: Disable nla so Guac work
    include: ./ps_disable_nla.yml
