---
  - name: Change Reg Key
    win_pc_registry:
      Ensure: Present
      Force: True
      Key: "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\User Shell Folders\\"
      ValueName: "{{ psfolders }}"
      ValueData: "\\\\KGSTRGUTL\\c$\\profiles\\{{ ps_user }}\\{{ psfolders }}"
      PsDscRunAsCredential_username: "{{ ps_user }}"
      PsDscRunAsCredential_password: "{{ ps_pass }}"
    loop_control:
      loop_var: psfolders
    with_items:
      - Desktop
      - Documents
      - Downloads
      - Music
      - Pictures
      - Favorites
