---
  - hosts: kg_ts1:kg_ts2
    vars:
      ps_domain_dict: {"10.255.10.20":"KGAD", "10.255.10.21":"KGSTRGUTL", "10.255.10.22":"KGTS1", "10.255.10.23":"KGTS2"}
    tasks:
      - debug: msg="{{ my_list[inventory_hostname] }}"
